<!------------------------产品轮播图start----------------------------------------------------->	
<?php if (count($this->getGalleryImages()) > 0): ?>
	<div class="swiper swiper-container" id="mobile_banner">
		<div class="swiper-wrapper">
		<?php foreach ($this->getGalleryImages() as $_image): ?>
			<div class="swiper-slide"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(FALSE)->resize(640); ?>" width="640" height="300" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" /></div>
		<?php endforeach; ?>
		</div>
		<div class="swiper-pagination"></div>
	</div>
<?php endif; ?>

<script>
var swiper = new Swiper('.swiper', {
	pagination: '.swiper-pagination',
	nextButton: '.swiper-button-next',
	prevButton: '.swiper-button-prev',
	paginationClickable: true,
	spaceBetween: 30,
	centeredSlides: true,
	autoplay: 2500,
	autoplayDisableOnInteraction: false,
	loop:true
});
</script>

<style>
   <!-- 手机端焦点图样式 -->
.swiper-container {
	width: 100%;
}
.swiper-container {
	margin-left: auto;
	margin-right: auto;
	position: relative;
	overflow: hidden;
	z-index: 1;
}
.swiper-wrapper {
	position: relative;
	width: 100%;
	height: 100%;
	z-index: 1;
	display: -webkit-box;
	display: -moz-box;
	display: -ms-flexbox;
	display: -webkit-flex;
	display: flex;
	-webkit-transition-property: -webkit-transform;
	-moz-transition-property: -moz-transform;
	-o-transition-property: -o-transform;
	-ms-transition-property: -ms-transform;
	transition-property: transform;
	-webkit-box-sizing: content-box;
	-moz-box-sizing: content-box;
	box-sizing: content-box;
}
.swiper-slide {
	text-align: center;
	font-size: 18px;
	background: #fff;
	display: -webkit-box;
	display: -ms-flexbox;
	display: -webkit-flex;
	display: flex;
	-webkit-box-pack: center;
	-ms-flex-pack: center;
	-webkit-justify-content: center;
	justify-content: center;
	-webkit-box-align: center;
	-ms-flex-align: center;
	-webkit-align-items: center;
	align-items: center;
}
.swiper-slide {
	-webkit-flex-shrink: 0;
	-ms-flex: 0 0 auto;
	flex-shrink: 0;
	width: 100%;
	height: 100%;
	position: relative;
}
.swiper-slide a,.swiper-slide-active a {
	display: block;
	width: 100%;
}

.swiper-slide a img,.swiper-slide-active a img {
	display: block;
	width: 100%;
}
.swiper-container-horizontal>.swiper-pagination-bullets, .swiper-pagination-custom, .swiper-pagination-fraction {
	bottom: 30px;
	left: 0;
	width: 100%;
}
.swiper-pagination {
	position: relative;
	text-align: center;
	-webkit-transition: .3s;
	-moz-transition: .3s;
	-o-transition: .3s;
	transition: .3s;
	-webkit-transform: translate3d(0, 0, 0);
	-ms-transform: translate3d(0, 0, 0);
	-o-transform: translate3d(0, 0, 0);
	transform: translate3d(0, 0, 0);
	z-index: 10;
}
.swiper-container-horizontal>.swiper-pagination-bullets .swiper-pagination-bullet {
	margin: 0 5px;
}
.swiper-pagination-clickable .swiper-pagination-bullet {
	cursor: pointer;
}
.swiper-pagination-bullet {

	width: 8px;
	height: 8px;
	display: inline-block;
	border-radius: 100%;
	background: #000;
	opacity: .2;
}
.swiper-pagination-bullet-active {
	opacity: 1;
	background: #1cce34;
}
.mian_home{ width:1080px; margin:0 auto;}
   <!-- 手机端焦点结束 -->

</style>